[WARN] [1753971272.930232532] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971272.999845484] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971273.100015092] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971273.197797020] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971273.297433924] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971273.397569868] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971273.498019925] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971273.597901117] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971273.697976165] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971273.799885422] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971273.898107062] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971273.999717983] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971274.097486796] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971274.197496986] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971274.298103785] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971274.400999993] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971274.497573797] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971274.597468436] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971274.697507138] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971274.797833649] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971274.897519679] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971274.997392493] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971275.097515169] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971275.197476182] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971275.297745418] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971275.398036063] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971275.498082707] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971275.597478247] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971275.698222460] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971275.798127921] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971275.898324549] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971275.921756305] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971275.999531546] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971276.022063911] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971276.097971732] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971276.122809890] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971276.198662382] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971276.221830556] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971276.298093065] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971276.322772183] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971276.398764867] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971276.421518769] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971276.497965629] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971276.521750411] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971276.598086264] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971276.621477958] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971276.697487666] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971276.721940128] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971276.798641165] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971276.821282042] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971276.897455719] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971276.921453749] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971276.997674914] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971277.021122736] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971277.097472290] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971277.122326258] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971277.197467170] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971277.222426066] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971277.300150884] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971277.321543666] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971277.397962371] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971277.421723315] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971277.497513668] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971277.522261236] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971277.597409572] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971277.622580404] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971277.698484229] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971277.721651732] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971277.797524261] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971277.823077846] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971277.898699142] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971277.921652213] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971277.997952166] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971278.021952663] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971278.097700717] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971278.121229917] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971278.197495923] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971278.221553092] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971278.297781626] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971278.322266539] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971278.397869088] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971278.422028689] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971278.497316486] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971278.526306427] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971278.597570061] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971278.621330686] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971278.697532788] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971278.721091204] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971278.797404250] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971278.821432843] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971278.899571394] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971278.921314833] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971278.998307240] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971279.021548025] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971279.097469075] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971279.122428198] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971279.198333153] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971279.221259058] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971279.297442700] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971279.321945343] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971279.397958169] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971279.421710283] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971279.498089830] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971279.522175512] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971279.598356211] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971279.621347588] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971279.699992128] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971279.721471473] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971279.797496235] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971279.821379933] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971279.897721080] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971279.921596490] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971279.998064261] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971280.021104087] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971280.097588214] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971280.122393451] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971280.197507177] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971280.223571006] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971280.298599484] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971280.321256143] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971280.397553998] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971280.423989188] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971280.500251683] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971280.521388756] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971280.597328531] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971280.623329384] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971280.698300390] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971280.721923610] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971280.797329784] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971280.821599884] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971280.898046955] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971280.921757919] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971280.997442781] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971281.021548242] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971281.097400853] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971281.120897802] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971281.197346126] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971281.221387395] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971281.299148296] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971281.321117275] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971281.397597663] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971281.421343892] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971281.497429207] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971281.522506414] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971281.597586064] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971281.621388005] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971281.698150153] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971281.722686687] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971281.807540202] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971281.821467478] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971281.901457597] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971281.921853903] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971281.998659443] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971282.021209032] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971282.097545936] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971282.122649896] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971282.200074001] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971282.221194501] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971282.297545837] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971282.322030661] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971282.397943724] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971282.421364418] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971282.497468106] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971282.521877793] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971282.597515273] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971282.621148031] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971282.697604455] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971282.721571966] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971282.804049740] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971282.821255516] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971282.897512964] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971282.921402171] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971283.001540359] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971283.021158682] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971283.100032458] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971283.121948608] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971283.197506860] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971283.222627045] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971283.298146065] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971283.321335464] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971283.397553109] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971283.423817839] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971283.498876922] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971283.521571953] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971283.597469981] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971283.621920982] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971283.697510402] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971283.721551226] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971283.798052583] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971283.821542302] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971283.898062379] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971283.921559011] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971283.997413903] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971284.022284457] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971284.099092987] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971284.121573395] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971284.198104260] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971284.221863966] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971284.297985999] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971284.325590444] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971284.397839801] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971284.421275986] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971284.497784579] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971284.521642941] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971284.598485871] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971284.622084168] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971284.697560056] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971284.722736371] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971284.797818787] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971284.821323100] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971284.897492461] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971284.921820615] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971284.998855001] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971285.020996145] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971285.098012968] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971285.124682630] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971285.198174584] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971285.221117394] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971285.297415656] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971285.321584963] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971285.398874042] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971285.421630515] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971285.497525577] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971285.521944708] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971285.597467577] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971285.622181173] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971285.697711850] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971285.723903463] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971285.797951706] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971285.821463221] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971285.897454314] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971285.921329925] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971285.997381114] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971286.021730551] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971286.097820113] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971286.121657421] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971286.197523527] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971286.222848037] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971286.297850941] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971286.321180793] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971286.397486643] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971286.421788048] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971286.498553323] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971286.521557478] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971286.597933856] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971286.622786942] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971286.698098391] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971286.721461459] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971286.797446796] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971286.821612905] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971286.897425731] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971286.921332543] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971286.997407609] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971287.021609303] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971287.097450005] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971287.121008402] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971287.197394609] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971287.221384399] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971287.297930094] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971287.321165291] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971287.397815850] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971287.421246919] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971287.497305766] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971287.522744517] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971287.597863075] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971287.621282144] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971287.697353694] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971287.722780958] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971287.797883739] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971287.821354968] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971287.897850615] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971287.923498551] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971287.997892403] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971288.021302066] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971288.097495029] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971288.121527508] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971288.197565655] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971288.221159286] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971288.298012634] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971288.321589144] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971288.397536955] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971288.421164442] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971288.497411517] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971288.524093312] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971288.597456223] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971288.623886754] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971288.697822082] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971288.721425985] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971288.797439875] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971288.824040102] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971288.897719558] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971288.921368357] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971288.997421448] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971289.025995950] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971289.097489776] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971289.134377058] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971289.197452439] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971289.221823801] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971289.298753377] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971289.322032449] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971289.397838888] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971289.422131177] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971289.497866768] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971289.521564912] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971289.597412535] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971289.622155545] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971289.697915072] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971289.721487584] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971289.797504712] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971289.821325384] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971289.897895984] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971289.921836913] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971289.997803512] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971290.021492089] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971290.097519525] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971290.121805512] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971290.197395571] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971290.221475445] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971290.298080578] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971290.321727331] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971290.400000370] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971290.421543537] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971290.497442045] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971290.522029824] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971290.598539916] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971290.621199948] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971290.697435897] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971290.722133852] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971290.797668551] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971290.821169448] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971290.897462356] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971290.922128119] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971290.997525922] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971291.021101445] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971291.097317462] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971291.121991226] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971291.197511978] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971291.221424173] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971291.297956574] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971291.321729889] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971291.397969074] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971291.422043349] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971291.497802373] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971291.522268873] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971291.597931769] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971291.622220989] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971291.697616333] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971291.722923346] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971291.797879937] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971291.827940045] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971291.897453172] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971291.921280887] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971291.997644168] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971292.022214573] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971292.097427009] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971292.122207175] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971292.197296154] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971292.221356127] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971292.297352724] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971292.320785368] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971292.397866383] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971292.422362804] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971292.498154793] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971292.521719565] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971292.597939714] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971292.621658630] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971292.699196093] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971292.721429088] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971292.799842872] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971292.821324377] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971292.897871215] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971292.921986740] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971292.997555176] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971293.024627507] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971293.097472967] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971293.121631437] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971293.197554663] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971293.221791469] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971293.298144775] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971293.321381068] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971293.398774823] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971293.422111725] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971293.497529125] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971293.521779468] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971293.598833062] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971293.621646315] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971293.698358949] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971293.721673994] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971293.799161414] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971293.823183308] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971293.897908483] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971293.921678057] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971293.997517986] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971294.022513899] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971294.099777227] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971294.122547441] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971294.199251023] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971294.221967093] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971294.298745204] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971294.324300638] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971294.399280634] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971294.422454240] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971294.497806141] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971294.522363334] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971294.597837314] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971294.622813804] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971294.698771273] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971294.722743505] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971294.798030445] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971294.821999509] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971294.899233877] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971294.921555194] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971294.998768889] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971295.021611808] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971295.098265155] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971295.123545327] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971295.197898030] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971295.222050487] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971295.297486680] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971295.321845474] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971295.400036424] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971295.424150865] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971295.498216080] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971295.523899996] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971295.598854620] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971295.621472003] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971295.697505381] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971295.721731950] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971295.799893140] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971295.821141464] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971295.897505179] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971295.922024741] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971295.997687079] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971296.021349808] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971296.097389655] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971296.122907908] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971296.197319624] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971296.221155026] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971296.297675001] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971296.321752836] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971296.399959054] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971296.423693976] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971296.497400219] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971296.521924678] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971296.599466351] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971296.621285206] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971296.698018878] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971296.721656935] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971296.797513294] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971296.822081561] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971296.898020576] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971296.922755691] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971296.997453776] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971297.021330331] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971297.097573798] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971297.123485078] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971297.197513117] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971297.221558665] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971297.297963188] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971297.323416867] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971297.397425994] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971297.421327830] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971297.498828164] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971297.520997196] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971297.598709658] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971297.621067043] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971297.697446383] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971297.721028090] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971297.797877318] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971297.821450705] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971297.897396444] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971297.921011431] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971298.001456570] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971298.021305984] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971298.097474255] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971298.121171644] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971298.197442892] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971298.221062840] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971298.297458376] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971298.321117237] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971298.397501925] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971298.421280306] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971298.497496545] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971298.521357550] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971298.597440062] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971298.621226315] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971298.697379514] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971298.729470839] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971298.797394999] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971298.821134884] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971298.897373171] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971298.921198464] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971298.997419056] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971299.021562367] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971299.098040467] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971299.121126624] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971299.197737493] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971299.225117706] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971299.297904952] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971299.321537958] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971299.397829210] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971299.421167111] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971299.497870428] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971299.521046409] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971299.597706910] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971299.621020076] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971299.697680385] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971299.720920814] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971299.797630371] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971299.821126449] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971299.897647557] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971299.920867218] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971299.997726184] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971300.020980150] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971300.097801008] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971300.121584671] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971300.197841048] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971300.221299015] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971300.297434847] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971300.322966514] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971300.397905576] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971300.421409047] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971300.498167345] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971300.521591936] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971300.598304825] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971300.621220679] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971300.697378976] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971300.721752368] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971300.797834313] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971300.821404440] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971300.897445776] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971300.921614304] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971300.997900249] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971301.021465321] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971301.097505126] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971301.121652279] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971301.197510228] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971301.221352933] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971301.297573506] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971301.321879092] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971301.421539553] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971301.522172592] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971301.621620637] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971301.722470060] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971301.821702969] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971301.923155369] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971302.021682485] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971302.123802957] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971302.222045469] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971302.321840081] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971302.421966884] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971302.521999704] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971302.621908460] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971302.721805983] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971302.821903251] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971302.921847398] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971303.023987328] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971303.121776212] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971303.222729360] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971303.322728137] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971303.422476034] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971303.522287131] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971303.625175642] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971303.724148721] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971303.825031853] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971303.921747839] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971304.022017370] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971304.122082649] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971304.222398425] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971304.322150039] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971304.421888918] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971304.521838965] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971304.621682292] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971304.721831795] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971304.821786834] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971304.921662705] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971305.021727761] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971305.121835286] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971305.221778555] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971305.321847360] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971305.421697028] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971305.521614121] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971305.621483053] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971305.721588434] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971307.492396247] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971307.494523164] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.354 7.983 7.06  0.975 0.656]
[ERROR] [1753971307.495369534] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971307.496758753] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[INFO] [1753971307.591877798] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971307.593940267] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.354 7.983 7.06  0.975 0.656]
[ERROR] [1753971307.594667916] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971307.595437614] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[INFO] [1753971307.692122742] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971307.693889243] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.354 7.983 7.06  0.975 0.656]
[ERROR] [1753971307.694603100] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971307.695359806] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[INFO] [1753971307.792021126] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971307.793710634] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.354 7.983 7.06  0.975 0.656]
[ERROR] [1753971307.794354892] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971307.795128974] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[INFO] [1753971307.892132599] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971307.893939451] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.983 7.06  0.975 0.656]
[ERROR] [1753971307.894652701] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971307.895523103] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[INFO] [1753971307.992295047] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971307.994134092] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.354 7.983 7.06  0.975 0.656]
[ERROR] [1753971307.994853645] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971307.995619919] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[INFO] [1753971308.092060316] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971308.093755744] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.354 7.983 7.06  0.975 0.656]
[ERROR] [1753971308.094427522] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971308.095190020] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[INFO] [1753971308.191803409] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971308.193418453] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.354 7.983 7.06  0.975 0.656]
[ERROR] [1753971308.194085271] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971308.194840249] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[INFO] [1753971308.292080232] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971308.293990476] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.354 7.983 7.06  0.975 0.656]
[ERROR] [1753971308.294721550] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971308.295478832] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[INFO] [1753971308.391783805] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971308.393437505] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.354 7.983 7.06  0.975 0.656]
[ERROR] [1753971308.394099299] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971308.394869829] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[INFO] [1753971308.492174516] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971308.494117849] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.983 7.06  0.975 0.656]
[ERROR] [1753971308.494824474] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971308.495584956] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[INFO] [1753971308.592087177] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971308.594216239] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.983 7.06  0.975 0.656]
[ERROR] [1753971308.594950704] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971308.595727314] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[INFO] [1753971308.692704481] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971308.694846182] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.983 7.06  0.975 0.656]
[ERROR] [1753971308.695548616] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971308.696352714] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[INFO] [1753971308.792421590] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971308.794389915] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.983 7.06  0.975 0.656]
[ERROR] [1753971308.795105341] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971308.795863646] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[INFO] [1753971308.892592300] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971308.894683249] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.983 7.06  0.975 0.656]
[ERROR] [1753971308.895382739] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971308.896180085] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971308.921771156] [solver_node]: 收到空的激光距离数据，跳过处理
[WARN] [1753971308.928880453] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971308.992072353] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971308.993964645] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.983 7.06  0.975 0.656]
[ERROR] [1753971308.994680903] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971308.995469833] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971309.022289900] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971309.092083740] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971309.093921632] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.983 7.06  0.975 0.656]
[ERROR] [1753971309.094633570] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971309.095423172] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971309.121149797] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971309.192077335] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971309.193838140] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.983 7.06  0.975 0.656]
[ERROR] [1753971309.194521373] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971309.195289919] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971309.222211651] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971309.293276598] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971309.295311291] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.983 7.06  0.975 0.656]
[ERROR] [1753971309.296016957] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971309.296821983] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971309.321608413] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971309.391690381] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971309.393384658] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.983 7.06  0.975 0.656]
[ERROR] [1753971309.394076659] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971309.394912278] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971309.421432504] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971309.492650987] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971309.494808433] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.983 7.06  0.975 0.656]
[ERROR] [1753971309.495506035] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971309.496439221] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971309.521771509] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971309.592351878] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971309.594328651] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.983 7.06  0.975 0.656]
[ERROR] [1753971309.595033581] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971309.595808495] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971309.631551657] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971309.691992609] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971309.693651397] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.983 7.06  0.975 0.656]
[ERROR] [1753971309.694315399] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971309.695134281] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971309.721373963] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971309.791599899] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971309.793134975] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.983 7.06  0.975 0.656]
[ERROR] [1753971309.793795617] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971309.794577091] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971309.821117670] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971309.892124440] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971309.893996477] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.975 0.656]
[ERROR] [1753971309.894823327] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971309.895615169] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971309.921620130] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971309.992002739] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971309.993946680] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.975 0.656]
[ERROR] [1753971309.994670074] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971309.995441180] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971310.021307006] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971310.092169396] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971310.093979577] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.975 0.656]
[ERROR] [1753971310.094704187] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971310.095501917] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971310.120998815] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971310.191657844] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971310.193287641] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.975 0.656]
[ERROR] [1753971310.193969722] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971310.194751132] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971310.220941408] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971310.292211287] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971310.294066844] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.975 0.656]
[ERROR] [1753971310.294795646] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971310.295585952] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971310.322059172] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971310.391980280] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971310.393773660] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.975 0.656]
[ERROR] [1753971310.394481822] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971310.395266272] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971310.421786564] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971310.492226233] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971310.494137630] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.975 0.656]
[ERROR] [1753971310.494955648] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971310.495804579] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971310.521042339] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971310.591834266] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971310.593646110] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.975 0.656]
[ERROR] [1753971310.594381728] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971310.595221154] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971310.621484646] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971310.692039003] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971310.693847648] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.975 0.656]
[ERROR] [1753971310.694573186] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971310.695354020] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971310.721057158] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971310.791891100] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971310.793665921] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.975 0.656]
[ERROR] [1753971310.794354978] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971310.795174981] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971310.821143719] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971310.892024094] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971310.893694658] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.975 0.656]
[ERROR] [1753971310.894356260] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971310.895173286] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971310.924546609] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971310.991823166] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971310.993484163] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.975 0.656]
[ERROR] [1753971310.994134788] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971310.994966694] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971311.021176395] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971311.092017477] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971311.093722282] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.975 0.656]
[ERROR] [1753971311.094392427] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971311.095200397] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971311.121089937] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971311.191688779] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971311.193292367] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.975 0.656]
[ERROR] [1753971311.193944945] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971311.194772787] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971311.221250201] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971311.292737653] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971311.294611226] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.975 0.656]
[ERROR] [1753971311.295303707] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971311.296090397] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971311.321849441] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971311.392192442] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971311.393985727] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.975 0.656]
[ERROR] [1753971311.394657664] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971311.395433731] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971311.421936168] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971311.491947904] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971311.493799877] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.975 0.656]
[ERROR] [1753971311.494542279] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971311.495350985] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971311.521193517] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971311.592025447] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971311.593806700] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.975 0.656]
[ERROR] [1753971311.594533838] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971311.595304336] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971311.621196404] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971311.692313103] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971311.694160340] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.984 7.06  0.975 0.656]
[ERROR] [1753971311.694895030] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971311.695672184] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971311.721251643] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971311.791875093] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971311.793698713] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.984 7.06  0.975 0.656]
[ERROR] [1753971311.794398907] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971311.795348734] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971311.821436674] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971311.891893851] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971311.893718400] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.984 7.06  0.975 0.656]
[ERROR] [1753971311.894417570] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971311.895234788] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971311.921075848] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971311.991534337] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971311.993176774] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.984 7.06  0.975 0.656]
[ERROR] [1753971311.993863047] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971311.994695946] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971312.020989840] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971312.091940398] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971312.093742931] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.984 7.06  0.975 0.656]
[ERROR] [1753971312.094452501] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971312.095241175] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971312.121200765] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971312.191694426] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971312.193709439] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.984 7.06  0.975 0.656]
[ERROR] [1753971312.194397921] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971312.195173091] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971312.221392234] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971312.292064488] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971312.293943469] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.984 7.06  0.975 0.656]
[ERROR] [1753971312.294687023] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971312.295474385] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971312.321177750] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971312.391702003] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971312.393418392] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.984 7.06  0.975 0.656]
[ERROR] [1753971312.394145114] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971312.395031516] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971312.421235618] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971312.491975296] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971312.493845797] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.984 7.06  0.975 0.656]
[ERROR] [1753971312.494568135] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971312.495358473] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971312.524982649] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971312.591617516] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971312.593448977] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.984 7.061 0.975 0.656]
[ERROR] [1753971312.594144083] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971312.594958869] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971312.622390494] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971312.692181658] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971312.694074239] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.984 7.061 0.975 0.656]
[ERROR] [1753971312.694798113] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971312.695585315] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971312.721199048] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971312.791737957] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971312.793379817] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.984 7.061 0.975 0.656]
[ERROR] [1753971312.794049547] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971312.794886925] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971312.821408917] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971312.892271283] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971312.894023608] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.984 7.061 0.975 0.656]
[ERROR] [1753971312.894748538] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971312.895545948] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971312.921259489] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971312.993729731] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971312.995917929] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.984 7.061 0.975 0.656]
[ERROR] [1753971312.996636043] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971312.997476589] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971313.021816880] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971313.092471601] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971313.094745496] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.984 7.061 0.975 0.656]
[ERROR] [1753971313.095698778] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971313.096856094] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971313.121570273] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971313.191811970] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971313.193583815] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.984 7.061 0.975 0.656]
[ERROR] [1753971313.194298345] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971313.195167595] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971313.221805588] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971313.292221333] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971313.294059578] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.984 7.061 0.975 0.656]
[ERROR] [1753971313.294800572] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971313.295616350] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971313.321484869] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971313.392094247] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971313.393808619] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.061 0.975 0.656]
[ERROR] [1753971313.394559662] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971313.395361616] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971313.421668248] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971313.492137177] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971313.493855454] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.061 0.975 0.656]
[ERROR] [1753971313.494575104] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971313.495410946] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971313.521435817] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971313.591911274] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971313.593674191] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.061 0.975 0.656]
[ERROR] [1753971313.594377393] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971313.595181459] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971313.621459643] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971313.692233629] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971313.694127971] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.061 0.975 0.656]
[ERROR] [1753971313.694858149] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971313.695691879] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971313.721495438] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971313.791995919] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971313.793821812] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.061 0.975 0.656]
[ERROR] [1753971313.794556086] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971313.795368984] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971313.821820577] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971313.891987649] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971313.893910982] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.061 0.975 0.656]
[ERROR] [1753971313.894735561] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971313.895584907] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971313.921450066] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971313.991709874] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971313.993511063] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.061 0.975 0.656]
[ERROR] [1753971313.994210297] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971313.994998491] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971314.021891462] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971314.092941261] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971314.094808370] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.061 0.975 0.656]
[ERROR] [1753971314.095627732] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971314.096433655] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971314.121701661] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971314.191757505] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971314.193552998] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.061 0.975 0.656]
[ERROR] [1753971314.194321096] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971314.195112427] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971314.222305591] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971314.292019962] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971314.293945151] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.061 0.973 0.656]
[ERROR] [1753971314.294686689] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971314.295560484] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971314.322122510] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971314.391887729] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971314.393505078] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.061 0.973 0.656]
[ERROR] [1753971314.394171511] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971314.394956538] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971314.421940677] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971314.492198410] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971314.494527280] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.061 0.973 0.656]
[ERROR] [1753971314.495574963] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971314.496673654] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971314.521478428] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971314.592037761] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971314.593926054] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.061 0.973 0.656]
[ERROR] [1753971314.594698280] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971314.595534091] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971314.621722772] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971314.692016345] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971314.693795678] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.061 0.973 0.656]
[ERROR] [1753971314.694531232] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971314.695389570] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971314.721451819] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971314.792818771] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971314.794561015] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.061 0.973 0.656]
[ERROR] [1753971314.795252249] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971314.796061276] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971314.821524739] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971314.891980552] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971314.893764653] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.061 0.973 0.656]
[ERROR] [1753971314.894466063] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971314.895213681] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971314.921325882] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971314.991742111] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971314.993326979] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.061 0.973 0.656]
[ERROR] [1753971314.993964581] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971314.994707847] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971315.021540083] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971315.092398014] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971315.094200995] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.061 0.973 0.656]
[ERROR] [1753971315.094906789] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971315.095692039] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971315.121576177] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971315.191693881] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971315.193289661] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.061 0.973 0.656]
[ERROR] [1753971315.193981887] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971315.194730242] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971315.221476910] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971315.292155703] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971315.294049565] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.061 0.973 0.656]
[ERROR] [1753971315.294776703] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971315.295550401] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971315.321522123] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971315.391753332] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971315.393398200] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.973 0.656]
[ERROR] [1753971315.394047258] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971315.394792412] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971315.421405704] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971315.492003666] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971315.493844471] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.973 0.656]
[ERROR] [1753971315.494555193] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971315.495379451] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971315.521343205] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971315.591745198] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971315.593454195] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.973 0.656]
[ERROR] [1753971315.594139765] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971315.594979767] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971315.621487715] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971315.692052652] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971315.693970002] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.973 0.656]
[ERROR] [1753971315.694709428] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971315.695503862] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971315.722562851] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971315.791739785] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971315.793321645] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.973 0.656]
[ERROR] [1753971315.793967951] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971315.794728433] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971315.821259901] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971315.892002311] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971315.893816716] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.973 0.656]
[ERROR] [1753971315.894522798] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971315.895314832] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971315.921161690] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971315.991614147] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971315.993166376] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.973 0.656]
[ERROR] [1753971315.993806729] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971315.994718412] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971316.021176057] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971316.091824166] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971316.093459051] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.973 0.656]
[ERROR] [1753971316.094114957] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971316.094878991] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971316.121195516] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971316.192022634] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971316.193712494] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.973 0.656]
[ERROR] [1753971316.194357744] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971316.195102483] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971316.226292461] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971316.292403726] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971316.294350163] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.973 0.656]
[ERROR] [1753971316.295063733] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971316.295851416] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971316.321694339] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971316.392119056] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971316.394134294] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.973 4.22 ]
[ERROR] [1753971316.394832056] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971316.395591322] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971316.426359027] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971316.492523380] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971316.494453977] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.973 4.22 ]
[ERROR] [1753971316.495169467] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971316.495946590] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971316.521190375] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971316.591884533] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971316.593820602] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.973 4.22 ]
[ERROR] [1753971316.594614013] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971316.595434623] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971316.621016362] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971316.692224249] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971316.694180094] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.973 4.22 ]
[ERROR] [1753971316.694912737] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971316.695695491] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971316.721983439] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971316.791851035] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971316.793596576] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.973 4.22 ]
[ERROR] [1753971316.794281282] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971316.795078308] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971316.821372304] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971316.892127006] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971316.893989284] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.973 4.22 ]
[ERROR] [1753971316.894723430] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971316.895508648] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971316.921061874] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971316.991790816] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971316.993549989] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.973 4.22 ]
[ERROR] [1753971316.994215847] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971316.995017130] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971317.021156695] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971317.092107433] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971317.094010927] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.973 4.22 ]
[ERROR] [1753971317.094753777] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971317.095559731] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971317.122047426] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971317.191880945] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971317.193606742] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.973 4.22 ]
[ERROR] [1753971317.194284056] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971317.195116346] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971317.221188168] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971317.292148570] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971317.294006912] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.973 4.22 ]
[ERROR] [1753971317.294739842] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971317.295525380] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971317.321337489] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971317.391728385] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971317.393427110] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.973 4.22 ]
[ERROR] [1753971317.394112264] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971317.394909867] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971317.420901976] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971317.491969035] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971317.493770608] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.973 4.22 ]
[ERROR] [1753971317.494512338] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971317.495302804] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971317.521412162] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971317.591923443] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971317.593658616] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.973 4.22 ]
[ERROR] [1753971317.594332890] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971317.595119740] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

[WARN] [1753971317.621385130] [solver_node]: 收到空的激光距离数据，跳过处理
[INFO] [1753971317.692153980] [solver_node]: 收到5个激光点，处理后5个有效点
[INFO] [1753971317.694521379] [solver_node]: 调用求解器前，distances shape: (5,), values: [0.355 7.985 7.06  0.973 4.22 ]
[ERROR] [1753971317.695291845] [solver_node]: 求解器调用失败: 距离数组长度(5)与激光配置数量(4)不匹配
[ERROR] [1753971317.696192200] [solver_node]: 详细错误信息: Traceback (most recent call last):
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/solver_node.py", line 93, in solve_loop
    solutions = self.solver.solve(self.distances)
  File "/home/orin/rc2025_ros2_ws/install/laser_solver/lib/python3.10/site-packages/laser_solver/positioning_algorithm/batch_pose_calculator.py", line 90, in solve
    raise ValueError(f"距离数组长度({len(distances)})与激光配置数量({len(self.laser_config)})不匹配")
ValueError: 距离数组长度(5)与激光配置数量(4)不匹配

